### ISSUE TITLE
babette sleeps/freezes/becomes unresponsive

### ISSUE THREAD

**Issue by AJFeng** [ropensci/babette#104]
I have hundreds BEAST tree need to run, then I wrote a for loop for the run_beast2 function. However, I found out many times, the program slept if I did not use the computer. I never had the program sleep problem before as I always run programs for many days (no matter R, python, or jar files. If I run the BEAST jar directly, it would not sleep). I tried two computers, and both slept. It did not stop the R program, it just sleep. Once I use the computer again, it will continue to run. Do any one know what the problem is?

**Comment by richelbilderbeek** [comment]
Hi @AJFeng, thanks for posting this Issue. 

Could you supply a [minimally reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

I predict it is not babette that causes the sleep, I predict it is BEAST2 or R that promps for user input. The latter happens on, among others, computer clusters.

Looking forward to the code!

Thanks and cheers, Richel

**Comment by richelbilderbeek** [comment]
Hi @AJFeng, thanks for the reply (and sorry I am late; I am usually more quick)

  1. For me to reproduce the problem, could you also share one of the XML files that causes the problem?
  2. Could you run `r beastier::is_beast2_input_file(input_filename)`?

I predict that the XML file uses a different version than `beastier` supports, and that -to comfirm this- `r beastier::is_beast2_input_file(input_filename)` returns `FALSE`.

Measuring is knowing :-)

**Comment by AJFeng** [comment]
beastier::is_beast2_input_file(paste0('./xml_file/',file_list[1])

return TRUE

**Comment by richelbilderbeek** [comment]
@AJFeng interesting. 

Great to know for sure that the XML file is correct. That removes it from the list. 

Still, I'd love to see that XML file with the real genetic data replaced by, for example, 3 dummy sequences. This would help me distinguish between 'freezing' and 'just taking a long time'. 

I do know `babette` checks the input quite carefully and that may take some time. 

And I know that using BEAGLE and 16 threads is **completely untested**. Does `babette` freeze without using BEAGLE? If that takes too long, remove all sequences but, say, 3. With three sequences, does `babette` freeze with BEAGLE?

Thanks for helping me get `babette` better. If this would result in a new unit test, I can guarantee the `babette` users more :-)

**Comment by richelbilderbeek** [comment]
This Issue has gone stale. Closing it!
