### ISSUE TITLE
Feature request: shifted gamma distribution

### ISSUE THREAD

**Issue by richelbilderbeek** [ropensci/babette#23]
From @dwinter:

> I don't think it possible to set a shifted gamma distribution (i.e. a gamma distribution with an additional "offset" value) yet. I didn't check others, but these shifted distributions are often helpful for setting node dates

**Comment by joelnitta** [comment]
Thanks for the useful package! I appreciate your efforts to make beauti more script-able.

How hard would this be to implement? I really need this option in my current analysis. Seems on the surface like it wouldn't be so hard to add `offset = XX` to a distribution spec, at least in the XML...

**Comment by richelbilderbeek** [comment]
Hi @joelnitta, thanks for reaching out! 

>  I appreciate your efforts to make beauti more script-able.

I struggle with understanding what it is that you want. Could you elaborate, preferably in another Issue, with an example of the code you would like to be able to write? 

If it is that you 'simply' want to specify an `offset` in the distributions in the same fashion as BEAUti does, I could definitely do that, if and only if you volunteer to check my work.

Feel encouraged to send me an email to schedule an online chat! I am always interested in meeting my users :-)

But hey, do create a new Issue: I even made a template for a Feature Request :-)

Cheers, Richel

**Comment by joelnitta** [comment]
Sure thing - I just thought the issue was already described here so didn't want to repeat.
I've opened a new issue in `beautier` https://github.com/ropensci/beautier/issues/130

**Comment by richelbilderbeek** [comment]
Hi @joelnitta: you were right, only now do I see the light :-) . Your new Issue is written down way better, so I will close this one! Thanks!
