### ISSUE TITLE
file.exists(output_log_filename) is not TRUE, on MacOS

### ISSUE THREAD

**Issue by thijsjanzen** [ropensci/babette#65]
Babette performs fairly weird behaviour on my (mac) machine. I executed the following:

```
crown_age <- 10
x <- TESS::tess.sim.taxa.age(n = 1, nTaxa = 20, age = crown_age, lambda = 1, mu=0)[[1]]
align <- phangorn::simSeq(x, l = 1000)

fasta_filename = "test.fasta"
phangorn::write.phyDat(
  align,
  file = fasta_filename,
  format = "fasta"
)

library(babette)

posterior <- bbt_run(
  fasta_filename,
  mcmc = create_mcmc(chain_length = 1000000, store_every = 5000),
  rng_seed = 42,
  verbose = TRUE,
  overwrite = TRUE
)
```
This causes babette to run BEAST 5 (five) times. At each restart the log/tree files are removed because overwrite=TRUE, and at the last run babette fails with:

```

"Bouckaert RR, Heled J, Kuehnert D, Vaughan TG, Wu C-H, Xie D, Suchard MA,"                                                                               
[80] "  Rambaut A, Drummond AJ (2014) BEAST 2: A software platform for Bayesian"                                                                               
[81] "  evolutionary analysis. PLoS Computational Biology 10(4): e1003537"                                                                                     
[82] ""                                                                                                                                                        
[83] "==============================================================================="                                                                         
[84] "Done!"                                                                                                                                                   
[1] "output_log_filename ('/var/folders/cz/dwggddxj7vs06byvsw1sh90w0000gp/T//RtmpxGoUZL/beast2_c573ee57b39log'): FALSE"
[1] "output_state_filename ('/var/folders/cz/dwggddxj7vs06byvsw1sh90w0000gp/T//RtmpxGoUZL/beast2_c574bfcfb71.xml.state'): TRUE"
[1] "output_trees_filenames ('/var/folders/cz/dwggddxj7vs06byvsw1sh90w0000gp/T//RtmpxGoUZL/beast2_test_c57244edf04.trees'): TRUE"
Error: file.exists(output_log_filename) is not TRUE
```

I would like to note that I have several installations of BEAST on my system (several versions etc). Could this interfere?
I did install BEAST using beastier (apart from previous manual installs), so at least one installation should be where babette expects it.

**Comment by richelbilderbeek** [comment]
Thanks for this great bug report! 

I will take a look at it soon, which is this Friday 17:30 at latest. I know that `babette` is tested under Windows, Mac and Linux, but most very rigorously under Linux. I will check if the relevant test is also run under MacOS, and if not, will let it do so. Else, I will use your code to reproduce this bug :-)

My only hypothesis now is that MacOS deletes temporary files faster: what if you'd store the log file somewhere local? Would this code below work? Note I use `bbt_run_from_model`, my preferred way to run `babette`.

```r
library(babette)

crown_age <- 10
x <- TESS::tess.sim.taxa.age(n = 1, nTaxa = 20, age = crown_age, lambda = 1, mu=0)[[1]]
align <- phangorn::simSeq(x, l = 1000)

fasta_filename = "test.fasta"
phangorn::write.phyDat(
  align,
  file = fasta_filename,
  format = "fasta"
)

posterior <- bbt_run_from_model(
  fasta_filename,
  inference_model = create_inference_model(
    mcmc = create_mcmc(chain_length = 1000000, store_every = 5000)
  ),
  beast2_options = create_beast2_options(
    rng_seed = 42,
    verbose = TRUE,
    overwrite = TRUE,
    output_log_filename = "my.trees"
  )
)
```

Could you check if this workd?

To answer your questions:

 * The reason BEAST2 is started 5 times is because BEAST2 also checks the input file to be correct. Apparently, it does so four times. 
 * Different versions of BEAST2 on your harddisc should not be a problem: if `beastier::install_beast2()` is run. it will take that one.

Let me know if the code above works (as a workaround at least), I'll check in more detail before Friday 17:30, after which I'll contact you.

Thanks again :+1:

**Comment by richelbilderbeek** [comment]
Could not resist fixing this ... :rainbow:

**Comment by thijsjanzen** [comment]
The workaround fixes this - specifying the log file helps.

**Comment by richelbilderbeek** [comment]
Happy to hear that! Still, it should work, thus I am testing this explicitly now... :muscle:

**Comment by richelbilderbeek** [comment]
Note to self: may be related to [this Issue](https://github.com/richelbilderbeek/pirouette/issues/96). If test passes, suggest him to update his versions :rainbow:

**Comment by richelbilderbeek** [comment]
I see in [the macOS build log](https://travis-ci.org/ropensci/babette/jobs/495508420#L980) that this works.

@thijsjanzen, does it work after updating all (in this order):

```r
usethis::install_github("ropensci/beautier")
usethis::install_github("ropensci/tracerer")
usethis::install_github("ropensci/beastier")
usethis::install_github("ropensci/mauricer")
usethis::install_github("ropensci/babette")
```

If yes or no, let me know :+1:

**Comment by thijsjanzen** [comment]
No, doesn't fix it.

(side-note; I used devtools::install_github, because:
`> usethis::install_github("ropensci/beautier")
Error: 'install_github' is not an exported object from 'namespace:usethis'` 
this was after installing the usethis package from github.

**Comment by richelbilderbeek** [comment]
In that case, I will put your code without modifications in a test... now.

**Comment by thijsjanzen** [comment]
BTW, interesting side-note: although with bbt_run_from_model you can specify the file names of the log file and the tree file, this only applies to the files _after the BEAST run_. During the BEAST run, BEAST still makes the "original" files, with the naming convention based on the fasta file (e.g. test.log for test.fasta etc). Those files are then removed at the end of the run, and replaced by the userspecified files, as far as I can see. Not the most elegant solution... (but it might have something to do with how BEAST handles things I imagine)

**Comment by richelbilderbeek** [comment]
@thijsjanzen: well spotted: I have to move files around due to the way BEAST2 handles files.

**Comment by richelbilderbeek** [comment]
Looking into this now...

**Comment by richelbilderbeek** [comment]
Works on my computer when run locally, but awaiting the Travis builds to have the last say.

```r
[1] "output_log_filename ('/tmp/RtmpJgToh5/beast2_23805220accalog'): TRUE"
[1] "output_state_filename ('/tmp/RtmpJgToh5/beast2_23803ad45c3a.xml.state'): TRUE"
[1] "output_trees_filenames ('/tmp/RtmpJgToh5/beast2_test_2380263a56c5.trees'): TRUE"
````

**Comment by richelbilderbeek** [comment]
Whatever I do, I cannot reproduce the error.

[This Travis CI build log for MacOS](https://travis-ci.org/ropensci/babette/jobs/496931316) passes.

This is the test run:

```r
test_that("file.exists(output_log_filename) is not TRUE, on MacOS, #65", {

  set.seed(42)
  crown_age <- 10
  x <- TESS::tess.sim.taxa.age(
    n = 1, nTaxa = 20, age = crown_age, lambda = 1, mu = 0
  )[[1]]
  align <- phangorn::simSeq(x, l = 1000)

  fasta_filename = "test.fasta"
  phangorn::write.phyDat(
    align,
    file = fasta_filename,
    format = "fasta"
  )

  beast2_output_log_filename <- tempfile(fileext = ".log")

  posterior <- bbt_run(
    fasta_filename,
    mcmc = create_mcmc(chain_length = 5000, store_every = 1000),
    rng_seed = 42,
    verbose = TRUE,
    overwrite = TRUE,
    beast2_output_log_filename = beast2_output_log_filename
  )

  posterior <- bbt_run(
    fasta_filename,
    mcmc = create_mcmc(chain_length = 5000, store_every = 1000),
    rng_seed = 42,
    verbose = TRUE,
    overwrite = TRUE
  )

  expect_true(file.exists(beast2_output_log_filename))
})
```

**Comment by richelbilderbeek** [comment]
@thijsjanzen: I am sorry for weird behaviour at your computer, but I cannot reproduce it. I will need your computer and become a knowledgeable MacOS user, before I have a chance to reproduce it.

I've mentioned a work-around that -according to you- works fine. 

I hope that is enough. If you find more bugs, please let me know. If you find out what caused this one, please let me know :+1: 

Not my proudest closed Issue...

**Comment by thijsjanzen** [comment]
Many thanks for looking into it, and providing the work around! 
I'm also unsure what causes the issue - it might indeed be something associated to my local machine.
Also, I just now noticed, that I'm running this in a directory being monitored by Dropbox - which complains about files being removed during the run. It might very well be that this is interfering with the workflow (e.g. Dropbox not unlocking a file for removal or so). 

I'm very happy to use babette right now though, happy user!

**Comment by richelbilderbeek** [comment]
I will add this suggestion to the docs, thanks!
