### ISSUE TITLE
Run NS package on win

### ISSUE THREAD

**Issue by SpelaBo** [ropensci/babette#68]
Exemplary xml from create_nested_sampling_mcmc vignette do not run on win. It causes error:

> run_beast2(beast2_input_file)
Error in check_input_filename_validity(input_filename = input_filename_full,  : 
  'input_filename' must be a valid BEAST2 XML file. File 'C:\Users\SpelaB\AppData\Local\Temp\RtmpGYzULP\file17660515735b.xml' is not a valid BEAST2 file. FALSE

If I understand correctly, here is the problem: https://github.com/CompEvol/beast2/issues/813. If I run the same xml from BEAST GUI it works.

**Comment by richelbilderbeek** [comment]
@SpelaBo: this is just awesome! Thanks so much for sharing, will add this when time.

**Comment by richelbilderbeek** [comment]
I cannot get it to work, already [reading an input file that uses the NS package](https://github.com/ropensci/babette/blob/develop/tests/testthat/test-nested_sampling.R) fails under Windows when using the jar with the added flag.

I give up for now :disappointed:

**Comment by richelbilderbeek** [comment]
Notes to self:

 - I do use newer version of Java on Travis instead of Java 8. I assume it is fine to use a newer version
 - I do not use

```
java -Dbeast.load.jars \path\to\BEAST\lib\beast.jar myfile.xml
```

but I use

```
java -jar -Dbeast.load.jars \path\to\BEAST\lib\beast.jar myfile.xml
```

instead. Running from `cmd.exe` results in an error if I do not add `-jar`.

**Comment by richelbilderbeek** [comment]
Too bad, cannot be done yet ...
