### ISSUE TITLE
Move 'pics' to 'man/figures'

### ISSUE THREAD

**Issue by jeroen** [ropensci/babette#80]
See https://docs.ropensci.org/babette/ and this comment from Hadley: https://github.com/ropensci/rotemplate/issues/19#issuecomment-506315565

You can also have a look at how other packages include readme figures:

 - https://github.com/ropensci/tidyhydat/
 - https://github.com/ropensci/drake/

**Comment by richelbilderbeek** [comment]
[Note from Jeroen](https://github.com/ropensci/babette/commit/8adf15a588c9cc63ae990c616414d6aa046cd3f3#commitcomment-36293669)

**Comment by jeroen** [comment]
I have fixed it for you in master: https://github.com/ropensci/babette/commit/b07cfe68ad9eb796f93d1c1c7bd5e35cbbf4d682
Now the site works and it's beautiful: https://docs.ropensci.org/babette/

Can you try to also fix the images for your other packages? 

 - https://docs.ropensci.org/beautier/
 - https://docs.ropensci.org/beastier/
 - https://docs.ropensci.org/mauricer/
 - https://docs.ropensci.org/tracerer/

**Comment by richelbilderbeek** [comment]
Thanks @jeroen! Will do so this Saturday :+1:

**Comment by richelbilderbeek** [comment]
Ah, just move all figures of `README.md` to `man/figures`, then update the links. Easy :rainbow:

**Comment by richelbilderbeek** [comment]
* [] beautier
 * [] beastier
 * [] tracerer
 * [] mauricer

**Comment by richelbilderbeek** [comment]
@jeroen: it has been done (one day though) :+1:

**Comment by jeroen** [comment]
Awesome, thanks!
