### ISSUE TITLE
Coding for population size initial, upper and lower parameters

### ISSUE THREAD

**Issue by GaryNapier** [ropensci/babette#92]
Hi Richèl, 

I was hoping you could point me in the right direction to code for the initial, upper and lower population size parameter in a Coalescent Constant Population model.

I'm currently trying to reproduce an analysis of a tuberculosis outbreak from this paper:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7725332/

I have the XML file and I have opened it in Beauti so that I can clearly see the parameters I need to reproduce. 

However I am stuck on:

Priors tab > Tree.t > Pop Size = 100 

And

popSize.t > initial = 100, upper = 200, lower = 0

Screenshot:

![Screen Shot 2021-03-03 at 11 29 20](https://user-images.githubusercontent.com/14896199/109799836-632cc280-7c14-11eb-862b-4f4659514e0f.png)

I can see in Babette that it's possible to code for the population size distribution, but I can't seem to find the initial, upper and lower parameters:

```
create_ccp_tree_prior(
  id = NA,
  pop_size_distr = beautier::create_log_normal_distr(id = NA, m = 1, s = 1.25)
)
```

Am I right in saying that ```id``` and ```pop_size_distr``` are the only arguments to ```create_ccp_tree_prior()```?

I'd like to know if this is possible, and if not, if you have suggestions for a workaround?

Actually, in general is there a way of parsing the paper's XML using Babette so that I can find what functions to use - in the same way that I've managed to load to XML into Beauti so I can see explicitly what parameters they've used?

Many thanks, 

Gary

**Comment by richelbilderbeek** [comment]
Hi Gary, thanks for this awesome bug report! 

The coalescent model is only a modestly tested model. And I'd be happy to fix this -probably- bug. Could you post  the BEAST2 XML file? And, will you volunteer to test if it indeed works?

If yes, I will probably fix it before Sunday 12:00 :+1:

**Comment by GaryNapier** [comment]
Hi Richèl, many thanks for getting back to me so quickly. 

Yes, I'd certainly be happy to test this! 

The XML file can be found here: https://github.com/GaryNapier/transmission/blob/main/beast_xml/BEAST2_GTR_Model_London_TB_Outbreak.xml

Ok, thanks for letting me know about the 'reverse' XML upload. 

It'd be good to have an online chat, thanks - I'm making my way through the "London study" XML and there are a couple of other settings/parameters that I doubt would be coded in Babette, so it might be quicker to let you know about these online. 

Many thanks! 

Gary

**Comment by richelbilderbeek** [comment]
Hi Gary, fun, lets meet online! You don't have an email on your GitHub profile, could you send a short email to me? We'll take care of things from there. Fun!

**Comment by richelbilderbeek** [comment]
P.S. The repo is private, so I cannot see it. You could make me a Collaborator :angel:

**Comment by GaryNapier** [comment]
Great, I'll send you and email then. 

Oh yes - I always forget about the private setting! haha

**Comment by richelbilderbeek** [comment]
Added at https://github.com/ropensci/beautier/issues/121, time for @GaryNapier to check my work :+1:

**Comment by GaryNapier** [comment]
Hi Richel, 

Many thanks again for your help, and so quick. 

I'm just trying to run `create_log_normal_distr()` again after running `remotes::install_github("ropensci/beautier")`. 

My code is:
```
beautier::create_log_normal_distr(
      m = 1,
      s = 1.25,
      initial_value=100.0,
      lower = 0.0,
      upper = 200.0
    )
```
But the `initial_value`, `lower` and 'upper` are described as unused arguments. 

When I run `?create_log_normal_distr` these arguments show up in the help file, but when I look at the function itself they don't seem to be there:

```
> create_log_normal_distr
function (id = NA, m = 0, s = 0) 
```
Perhaps the function hasn't been pushed to Github or something?

Thanks!

**Comment by richelbilderbeek** [comment]
Silly me, will fix tonight and send an email when done. Thanks for checking me :blush:

**Comment by GaryNapier** [comment]
haha cheers!

**Comment by richelbilderbeek** [comment]
Added the trivial test below, which works:

```r
test_that("log_normal_distr, complete use", {
  m <- 1.0
  s <- 1.25
  value <- 100.0
  lower <- 0.01
  upper <- 200.0
  log_normal_distr <- create_log_normal_distr(
    m = m,
    s = s,
    value = value,
    lower = lower,
    upper = upper
  )
  expect_equal(m, log_normal_distr$m$value)
  expect_equal(s, log_normal_distr$s$value)
  expect_equal(value, log_normal_distr$value)
  expect_equal(lower, log_normal_distr$lower)
  expect_equal(upper, log_normal_distr$upper)
})
```

Whatever it was. it is fixed now :+1:

**Comment by richelbilderbeek** [comment]
It works, except there is another Issue at #93.
