### ISSUE TITLE
Doubling of clockPrior ID

### ISSUE THREAD

**Issue by richelbilderbeek** [ropensci/babette#94]
Follow-up from #93:

Thanks @GaryNapier for this report.

![111988076-eb153680-8b07-11eb-8062-46c2ce0a7a7a](https://user-images.githubusercontent.com/2098230/111991063-2c134800-8b14-11eb-9606-33371a373466.png)

**Comment by richelbilderbeek** [comment]
Here is the problem, from the error 
[issue_94.txt](https://github.com/ropensci/babette/files/6182231/issue_94.txt)



```
<distribution id="posterior" spec="util.CompoundDistribution">
    <distribution id="prior" spec="util.CompoundDistribution">
        <distribution id="YuleModel.t:THAILAND_TEST.clust_1.dated" spec="beast.evolution.speciation.YuleModel" birthDiffRate="@birthRate.t:THAILAND_TEST.clust_1.dated" tree="@Tree.t:THAILAND_TEST.clust_1.dated"/>
        # ...
        <prior id="ClockPrior.c:THAILAND_TEST.clust_1.dated" name="distribution" x="@clockRate.c:THAILAND_TEST.clust_1.dated">
            <Uniform id="Uniform.150" name="distr" upper="Infinity"/>
        </prior>
        # ...
        <prior id="ClockPrior.c:THAILAND_TEST.clust_1.dated" name="distribution" x="@clockRate.c:THAILAND_TEST.clust_1.dated">
            <LogNormal id="LogNormalDistributionModel.0" name="distr">
                <parameter id="RealParameter.0" estimate="false" name="M">1</parameter>
                <parameter id="RealParameter.1" estimate="false" lower="0" name="S" upper="Infinity">1.25</parameter>
            </LogNormal>
        </prior>
    </distribution>
</distribution>
```

**Comment by richelbilderbeek** [comment]
This Issue appears fixed.

**Comment by richelbilderbeek** [comment]
I predict due to test at https://github.com/ropensci/beastier/commit/c18fd28a7d618a1aab323bf3ac3b895f5c629f64 that this is fixed.

**Comment by richelbilderbeek** [comment]
I predict due to test at https://github.com/ropensci/beastier/commit/c18fd28a7d618a1aab323bf3ac3b895f5c629f64 that this is fixed.

**Comment by GaryNapier** [comment]
Thanks Richel, I will test soon.

**Comment by GaryNapier** [comment]
Thanks Richel, I think this has worked! No errors when I run my original code from my previous issue.

**Comment by richelbilderbeek** [comment]
Awesome! Thanks so much for checking my work!

Happily closing this Issue :+1:
